version: 0.2

phases:

install:

runtime-versions:

java: corretto8

pre_build:

commands:

- echo In the pre_build phase...

build:

commands:

- echo Build started on1 `date`

- mvn test

post_build:

commands:

- echo Build complete on1 `date`

- mvn package

artifacts:

files:

- target/mvnwebapp.war
